[package]
name = "vqa"
version = "0.5.1"
authors = ["Mack Stump <mack@mackstump.com>"]
edition = "2024"
description = "Parser and decoder for Westwood Studios' VQA (Vector Quantized Animation) full-motion-video format"
homepage = "https://github.com/smackysnacks/vqa"
repository = "https://github.com/smackysnacks/vqa"
documentation = "https://docs.rs/vqa/"
license = "MIT"
readme = "README.md"
keywords = ["vqa", "westwood", "parser", "video", "adpcm"]
categories = [
  "parser-implementations",
  "multimedia::video",
  "multimedia::audio",
]
include = ["/src", "/examples/*.rs", "/LICENSE", "/README.md"]

[dependencies]
bitflags = "2"
nom = "8"

[dev-dependencies]
cpal = "0.18"
minifb = "0.28"
