[package]
name = "vqa-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.vqa]
path = ".."

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "adpcm"
path = "fuzz_targets/adpcm.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lcw"
path = "fuzz_targets/lcw.rs"
test = false
doc = false
bench = false
